### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by ekaitz-zarraga** [SlimerDude/afHtmlParser#1]
Hi,

I'm reusing the PEG grammar and I need to make sure the license of that is compatible with my project.

I found no license file in the repository, could you please add one?

I would suggest a GPL compatible license.

**Comment by SlimerDude** [comment]
Hi, there should be little tag / image at the top of the home page that states the licence is ISC - linking to: https://choosealicense.com/licenses/isc/

![image](https://github.com/user-attachments/assets/d3a679f0-9c20-4311-801c-6c4d0d7aa556)

ISC is essentially MIT, but with fewer words.

Hope this helps,

Steve.

**Comment by ekaitz-zarraga** [comment]
Oh I just didn't watch it because there's no specific file for it!
Thanks!

**Comment by ekaitz-zarraga** [comment]
Please consider adding the name of the author, and the copyright years.
It's when the work is redistributed.
